name: CI

on:  
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:  
  build:    
    runs-on: windows-latest
    
    env:
      config: 'UnitTests'
    
    steps:      
      - uses: actions/checkout@v2
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        
      - name: Setup VSTest
        uses: darenm/Setup-VSTest@v1

      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE

      - name: Restore Packages
        run: nuget restore .\src\InventorPlugin.sln

      - name: Build Solution
        run: |
          msbuild.exe .\src\InventorPlugin.sln /p:platform="Any CPU" /p:configuration="UnitTests"
        
      - name: Run UnitTests
        run: |
          vstest.console.exe /?
          vstest.console.exe .\src\TestBuilder\bin\UnitTests\TestBuilder.dll /Framework:".NETFramework,Version=v4.7.2"
          vstest.console.exe .\src\TestCore\bin\UnitTests\TestCore.dll /Framework:".NETFramework,Version=v4.7.2"
          vstest.console.exe .\src\TestFenceBuildingVm\bin\UnitTests\TestFenceBuildingVm.dll /Framework:".NETFramework,Version=v4.7.2"
