name: CI

on:  
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:  
  build:    
    runs-on: windows-latest
    
    steps:      
      - uses: actions/checkout@v2
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        
      - name: Setup VSTest
        uses: darenm/Setup-VSTest@v1

      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE

      - name: Restore Packages
        run: nuget restore .\src\InventorPlugin.sln

      - name: Build TestBuilder
        run: |
          msbuild.exe .\src\TestBuilder\*.csproj /p:platform="Any CPU" /p:configuration="Release"
          msbuild.exe .\src\TestCore\*.csproj /p:platform="Any CPU" /p:configuration="Release"
          msbuild.exe .\src\TestFenceBuildingVm\*.csproj /p:platform="Any CPU" /p:configuration="Release"
        
      - name: Run TestBuilder
        run: |
          vstest.console.exe .\src\TestBuilder\bin\Release\TestBuilder.dll
          vstest.console.exe .\src\TestCore\bin\Release\TestCore.dll
          vstest.console.exe .\src\TestFenceBuildingVm\bin\Release\TestFenceBuildingVm.dll
